Don't assume window exists
Logflare/pino-logflare pull request #61
Opened 2023-01-09 21:01 UTC by maccman

Window is not defined in workers.

2023-02-19 11:07 UTC, ImLunaHey commented
Should this not return the worker location in the case of a worker?

2023-06-07 08:09 UTC, Ziinc requested changes

2023-06-07 08:09 UTC, Ziinc commented
covering the workers would be a plus but not essential for this PR to get merged.

2023-06-07 08:22 UTC, Ziinc approved these changes
merging this in first.

2023-06-07 08:22 UTC, merged